AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GraphQL APIs for my personal blog.

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: blogs
        LAMBDA_AWS_REGION: ap-southeast-1 
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  # create a custom handler to return 200 and appropriate headers for your OPTIONS requests
  # OptionsFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: options-handler
  #     Handler: index.options #nodejs
  #     Events:
  #       Options:
  #         Type: Api
  #         Properties:
  #           Path: /{cors+}
  #           Method: OPTIONS
  #           Auth:
  #             Authorizer: NONE
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.graphqlHandler
      FunctionName: GraphqlFunction
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /graphql
            Method: post

  CommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: blog-comments
      AttributeDefinitions:
        - AttributeName: blogId
          AttributeType: S
        - AttributeName: commentId
          AttributeType: S
      KeySchema:
        - AttributeName: blogId
          KeyType: HASH
        - AttributeName: commentId
          KeyType: RANGE
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5

  ViewTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: blog-views
      AttributeDefinitions:
        - AttributeName: blogId
          AttributeType: S
        - AttributeName: viewAt
          AttributeType: S
      KeySchema:
        - AttributeName: blogId
          KeyType: HASH
        - AttributeName: viewAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
