AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GraphQL APIs for my personal blog.

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: comments
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.graphqlHandler
      FunctionName: GraphqlFunction
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /graphql
            Method: post

  CommentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: commments
      PrimaryKey:
         Name: id
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5

Outputs:
  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
